Implemented the String class
Ortemki/phplab-tasks-2022 pull request #1
Opened 2022-08-15 09:04 UTC by Ortemki

2022-08-15 23:07 UTC, Kloud333 requested changes

2022-08-15 23:07 UTC, Kloud333 commented on src/strings/Strings.php
> +
Зайвий пустий рядок.

2022-08-15 23:07 UTC, Kloud333 commented on src/strings/Strings.php
> +
Зайвий пустий рядок.

2022-08-15 23:07 UTC, Kloud333 commented on src/strings/Strings.php
> +
Зайвий пустий рядок.

2022-08-15 23:07 UTC, Kloud333 commented on src/strings/Strings.php
> +        $firstStr = mb_convert_case(str_replace("_", " ", $input), MB_CASE_TITLE);
Думаю тут можна обійтись без mb_convert_case. 
І спробуй щаписати все одним рядком.

2022-08-15 23:07 UTC, Kloud333 commented on src/strings/Strings.php
> +        foreach ($wordsArr as $word){
Спробуй розділити код. Доволі погано читається. Додай пропуски між змінними, foreach, return, etc. . .

2022-08-15 23:07 UTC, Kloud333 commented on src/strings/Strings.php
> +        $firstLetter = $noun[0];
Змінні - $firstLetter та $lastLetter - тут не потрібні.

2022-08-15 23:07 UTC, Kloud333 commented on src/strings/Strings.php
> +        if($firstLetter === $lastLetter) {
Спробуй переписати if так, щоб не було else і тільки 1 return.

2022-08-16 10:43 UTC, Ortemki commented on src/strings/Strings.php
> +
Удалил пустой рядок.

2022-08-16 10:44 UTC, Ortemki commented on src/strings/Strings.php
> +
Удалил пустой рядок.

2022-08-16 10:44 UTC, Ortemki commented on src/strings/Strings.php
> +
Удалил пустой рядок.

2022-08-16 10:44 UTC, Ortemki commented on src/strings/Strings.php
> +        $firstStr = mb_convert_case(str_replace("_", " ", $input), MB_CASE_TITLE);
Убрал функцию mb_convert_case и записал все в один рядок.

2022-08-16 10:45 UTC, Ortemki commented on src/strings/Strings.php
> +        foreach ($wordsArr as $word){
Постарался повысить читабельность кода.

2022-08-16 10:46 UTC, Ortemki commented on src/strings/Strings.php
> +        $firstLetter = $noun[0];
Убрал лишние переменные.

2022-08-16 10:49 UTC, Ortemki commented on src/strings/Strings.php
> +        if($firstLetter === $lastLetter) {
Переписал код, так что бы остался один return но не смог убрать else. Не до конца представляю как оставить только один return без else.
И оставил закомментированным вариант решения в одну строчку.

2022-08-19 19:55 UTC, Kloud333 approved these changes

2022-08-19 19:55 UTC, Kloud333 commented on src/strings/Strings.php
> +        $wordsArr = explode(" ", $input);
Старайся не використовувавти подвійні лакпи "" - краще одинарні - ''. 
Виправляти не потрібно.

2022-08-19 19:55 UTC, Kloud333 commented on src/strings/Strings.php
> +        return ($noun[0] === $noun[-1]) ? (ucfirst($noun) . substr($noun, 1)) : ("The " . ucfirst($noun));
Обгортати в дужки як умову так і вирази не потрібно **($noun[0] === $noun[-1]) => $noun[0] === $noun[-1]**

2022-08-20 10:34 UTC, Ortemki commented on src/strings/Strings.php
> +        return ($noun[0] === $noun[-1]) ? (ucfirst($noun) . substr($noun, 1)) : ("The " . ucfirst($noun));
Убрал лишние дужки.

2022-08-20 10:34 UTC, Ortemki commented on src/strings/Strings.php
> +        $wordsArr = explode(" ", $input);
На всякий также исправил и лапки.

2022-08-28 15:41 UTC, merged