Implemented classes Basics and BasicsValidator
Ortemki/phplab-tasks-2022 pull request #2
Opened 2022-08-15 09:05 UTC by Ortemki

2022-08-15 23:00 UTC, Kloud333 requested changes

2022-08-15 23:00 UTC, Kloud333 commented on src/basics/Basics.php
> +        $this->validator->isYearException($year);
Потрібен пустий рядок після валідатора.

2022-08-15 23:00 UTC, Kloud333 commented on src/basics/Basics.php
> +        $this->validator->isValidStringException($input);
Потрібен пустий рядок після валідатора.

2022-08-15 23:00 UTC, Kloud333 commented on src/basics/Basics.php
> +        if($firstPart == $secondPart){
Спробуй забрати if і залишити 1 return.

2022-08-16 10:57 UTC, Ortemki commented on src/basics/BasicsValidator.php
> +<?php
Сделал.

2022-08-16 10:57 UTC, Ortemki commented on src/basics/BasicsValidator.php
> +
Убрал лишний рядок.

2022-08-16 10:58 UTC, Ortemki commented on src/basics/BasicsValidator.php
> +        try{
Исправил throw InvalidArgumentException.

2022-08-16 10:59 UTC, Ortemki commented on src/basics/BasicsValidator.php
> +            if($minute < 0 OR $minute > 59){
Убрал **if** и вместо использовал функции **in_array** and **range**.

2022-08-16 11:00 UTC, Ortemki commented on src/basics/BasicsValidator.php
> +            if(strlen($input) > 6 ){
Не до конца понял в чем недостаток данной проверки но заменил на **mb_strlen**.

2022-08-16 11:07 UTC, Ortemki commented on src/basics/BasicsValidator.php
> +
Убрал ненужные рядки.

2022-08-16 11:08 UTC, Ortemki commented on src/basics/Basics.php
> +
Убрал.

2022-08-16 11:08 UTC, Ortemki commented on src/basics/Basics.php
> +<?php
Исправил форматирование.

2022-08-16 11:09 UTC, Ortemki commented on src/basics/Basics.php
> +        if($minute >= 1 AND $minute <=15){
Вместо **AND** использовал функции **in_array** i **range**

2022-08-16 11:10 UTC, Ortemki commented on src/basics/Basics.php
> +        switch ($leapYear) {
Переписал. И смог сократить до 2 строк.

2022-08-16 11:10 UTC, Ortemki commented on src/basics/Basics.php
> +}
Оставил пустой рядок в конце файла.

2022-08-16 11:10 UTC, Ortemki commented on src/basics/Basics.php
> +        $this->validator->isYearException($year);
Добавил пустые рядки после валидаторов.

2022-08-16 11:11 UTC, Ortemki commented on src/basics/Basics.php
> +        $this->validator->isValidStringException($input);
Добавил необходимый рядок.

2022-08-16 11:11 UTC, Ortemki commented on src/basics/Basics.php
> +        if($firstPart == $secondPart){
Оставил только один **return**.

2022-08-19 19:48 UTC, Kloud333 requested changes

2022-08-19 19:48 UTC, Kloud333 commented on src/basics/Basics.php
> +use Webmozart\Assert\InvalidArgumentException;
Де використовуєш цей **InvalidArgumentException**? 🙂

2022-08-19 19:48 UTC, Kloud333 commented on src/basics/Basics.php
> +        if(in_array($minute, range(1,15))){
**in_array** і **range** - також поганий варіант. Замість простого логічного оператора, ти використовуєш дві функції. Що явно не буде на користь швидкодії. 🙂У минулому коментарі мав на увазі заміть оператора "**AND**" використати новішу версію "**&&**".

2022-08-19 19:48 UTC, Kloud333 commented on src/basics/Basics.php
> +        return date("L", mktime(0, 0, 0, 7, 7, $year));
Тут також можна виконати без додаткової функції date. Можна використати прості логічні оператори. 
Мав на увазі так - **return ($year % 400 === 0) || (($year % 100 !== 0) && ($year % 4 === 0));**

2022-08-19 19:48 UTC, Kloud333 commented on src/basics/Basics.php
> +        return $firstPart == $secondPart;
Додай пустий рядок перед **return**.

2022-08-19 19:48 UTC, Kloud333 commented on src/basics/Basics.php
> +        $this->validator->isValidStringException($input);
Цей валідатор працює не правильно. 
Тест - **.\vendor\bin\phpunit --filter=IsSumEqualTest** - не проходить.

2022-08-19 19:48 UTC, Kloud333 commented on src/basics/BasicsValidator.php
> +        if (mb_strlen($input) > 6) {
Тут щось теж не правильно. . . 😏

2022-08-20 10:21 UTC, Ortemki commented on src/basics/Basics.php
> +use Webmozart\Assert\InvalidArgumentException;
Удалил ненужный рядок.

2022-08-20 10:21 UTC, Ortemki commented on src/basics/Basics.php
> +        if(in_array($minute, range(1,15))){
Исправил условия.

2022-08-20 10:22 UTC, Ortemki commented on src/basics/Basics.php
> +        return date("L", mktime(0, 0, 0, 7, 7, $year));
Понял. В файле заменил на предложенное тобой решение.

2022-08-20 10:22 UTC, Ortemki commented on src/basics/Basics.php
> +        return $firstPart == $secondPart;
Добавил рядок.

2022-08-20 10:26 UTC, Ortemki commented on src/basics/Basics.php
> +        $this->validator->isValidStringException($input);
Вроде бы с этим тестом есть ошибка ?! В BasicsInterface к функции isSumEqual необходима проверка и выброс InvalidArgumentException если будет введено больше шести символов. Но в самом тесте стоит проверка в случае ввода 4 символов.

2022-08-27 22:02 UTC, Kloud333 commented on src/basics/Basics.php
> +use Webmozart\Assert\InvalidArgumentException;
Добре. 👍

2022-08-27 22:02 UTC, Kloud333 commented on src/basics/Basics.php
> +        if(in_array($minute, range(1,15))){
Добре 👍

2022-08-27 22:03 UTC, Kloud333 commented on src/basics/Basics.php
> +        return date("L", mktime(0, 0, 0, 7, 7, $year));
Добре 👍

2022-08-27 22:06 UTC, Kloud333 commented on src/basics/Basics.php
> +        $this->validator->isValidStringException($input);
Нажаль ні, у тесті усе правильно, ми маємо тестувати і з 4 символами. Якраз тоді і вилітає ексепшин. Просто у валідаторі має бути умова != 6.

2022-08-27 22:07 UTC, Kloud333 commented on src/basics/BasicsValidator.php
> +        if (mb_strlen($input) > 6) {
Якраз і натякав на умову.

2022-08-27 22:08 UTC, Kloud333 approved these changes

2022-08-28 15:40 UTC, merged