Implemented the class Arrays with its functions
Ortemki/phplab-tasks-2022 pull request #3
Opened 2022-08-17 10:39 UTC by Ortemki

2022-08-19 20:13 UTC, Kloud333 requested changes

2022-08-19 20:13 UTC, Kloud333 commented on src/arrays/Arrays.php
> +        return array_merge($input, array_reverse($input));
Тест .\vendor\bin\phpunit --filter=RepeatArrayValuesTest не проходить.
Код не робочий.

2022-08-19 20:13 UTC, Kloud333 commented on src/arrays/Arrays.php
> +    public function getUniqueValue(array $input): int
Тут усе дуже погано.  3 if і ще foreach з if у середині і 3 return. Погана логіка і код зовсім не читабельний. 

Спробуй переробити даний код так, щоб був тільки 1 return.
Підказка функція array_diff - може стати у пригоді.

2022-08-19 20:13 UTC, Kloud333 commented on src/arrays/Arrays.php
> +        $newArr = [];
$newArr - погана назва змінної. Ніколи не називай змінні скорочено, або не зрозуміло. Потім тяжко визначити для чого вона. 
$ele - і це теж.

2022-08-19 20:13 UTC, Kloud333 commented on src/arrays/Arrays.php
> +        foreach($newArr as &$tag){
Спробуй позбутись цього foreach.

2022-08-20 12:39 UTC, Ortemki commented on src/arrays/Arrays.php
> +
Удалил его.

2022-08-20 12:40 UTC, Ortemki commented on src/arrays/Arrays.php
> +        return array_merge($input, array_reverse($input));
Изначально неправильно понял суть задачи. Теперь реализовал то что необходимо.

2022-08-20 12:42 UTC, Ortemki commented on src/arrays/Arrays.php
> +    public function getUniqueValue(array $input): int
Переделал код этой функции.

2022-08-20 12:43 UTC, Ortemki commented on src/arrays/Arrays.php
> +        $newArr = [];
Изменил название массива $newArr и дописал названия переменной $ele.

2022-08-20 12:43 UTC, Ortemki commented on src/arrays/Arrays.php
> +        foreach($newArr as &$tag){
Заменил foreach на array_walk.

2022-08-27 22:11 UTC, Kloud333 commented on src/arrays/Arrays.php
> +
Добре 👍

2022-08-27 22:18 UTC, Kloud333 commented on src/arrays/Arrays.php
> +    public function getUniqueValue(array $input): int
Вже краще набагато 👍, але можна обійтись і без if і без змінної. 
Як тобі такий варіант? 

            $uniqueValues = array_diff($input, array_diff_assoc($input, array_unique($input)));
            return $uniqueValues ? min($uniqueValues) : 0;

Твій же ж код, але без зайвих перевірок.

2022-08-27 22:21 UTC, Kloud333 commented on src/arrays/Arrays.php
> +        foreach($newArr as &$tag){
Уже кращий варіант, але насправді можна було просто посортувати перед тим, як проходитись по тегах.

Твій же ж код, аде замість array_walk просто sort перед foreach.

        $result = [];
        
        sort($input);

        foreach ($input as $product) {
            foreach ($product['tags'] as $tag) {
                $result[$tag][] = $product['name'];
            }
        }

        ksort($result);

        return $result;

2022-08-27 22:23 UTC, Kloud333 commented on src/arrays/Arrays.php
> +        return array_merge($input, array_reverse($input));
Добре 👍

2022-08-27 22:24 UTC, Kloud333 commented on src/arrays/Arrays.php
> +        $newArr = [];
Добре 👍

2022-08-27 22:25 UTC, Kloud333 approved these changes

2022-08-28 15:42 UTC, merged