Completed tasks on WEB
Ortemki/phplab-tasks-2022 pull request #6
Opened 2022-08-29 10:56 UTC by Ortemki

Implemented the main functionality but I will still work on the syntax.

2022-09-01 22:00 UTC, Kloud333 requested changes

2022-09-01 22:00 UTC, Kloud333 commented on src/web/functions.php
> +    foreach ($airports as $airport){
Я б спробував замінити `foreach` на `array_map` і `array_unique`. Вийшло б компактніше.

2022-09-01 22:00 UTC, Kloud333 commented on src/web/index.php
> +function filterByLetter(array $airports,string $letter)
Замість того, щоб створювати окрему функцію, я б використав - `array_filter`.

2022-09-01 22:00 UTC, Kloud333 commented on src/web/index.php
> +function filterByState(array $airports, string $state)
Замість того, щоб створювати окрему функцію, я б використав - `array_filter`.

2022-09-01 22:00 UTC, Kloud333 commented on src/web/index.php
> +function sortBy($param)
Не дуже доільно створювати окрему функцію для цього. Можна виконати ці дія як колбек функція.

2022-09-01 22:00 UTC, Kloud333 commented on src/web/index.php
> +function sortAirportsBy($airports, $param)
Замість цієї функції я б використов - `usort` з колбек функцією вище.

2022-09-01 22:00 UTC, Kloud333 commented on src/web/index.php
> +            <a href="?filter_by_first_letter=<?= $letter ?><?=$letterHref?>"><?= $letter ?></a>
Тут порекомендував би глянути у сторону функції - `http_build_query`.

2022-09-01 22:00 UTC, Kloud333 commented on src/web/index.php
> +            <th scope="col"><a href="<?= $sortHref ?>sort=name">Name</a></th>
`http_build_query`

2022-09-01 22:35 UTC, Kloud333 requested changes

2022-09-01 22:35 UTC, Kloud333 commented on src/web/functions.php
>  function getUniqueFirstLetters(array $airports)
Не бачу `PhpUnit` теста для цієї функції.

2022-09-09 18:56 UTC, Kloud333 requested changes

2022-09-09 18:56 UTC, Kloud333 commented on src/web/functions.php
>  function getUniqueFirstLetters(array $airports)
Добре 👍

2022-09-09 18:56 UTC, Kloud333 commented on src/web/functions.php
> +    $letters = array_unique(array_map($firstLetter, $airports));
`array_map` має можливість використовувати `callback` функцію - можна скомбінувати ту функцію, що написав ти і `array_map`.

```
    $letters = array_unique(array_map(function ($airport) {
        return $airport['name'][0];
    }, $airports));
```

2022-09-09 18:56 UTC, Kloud333 commented on src/web/index.php
> +    $airports = array_filter(
І тут я б поправив форматування на таке - 

```
    $airports = array_filter($airports, function ($airport) {
        return $airport['name'][0] == $_GET['filter_by_first_letter'];
    });
```

2022-09-09 18:56 UTC, Kloud333 commented on src/web/index.php
> +    $letter = $_GET['filter_by_first_letter'];
Думаю ця змінна не потрібна.

2022-09-09 18:56 UTC, Kloud333 commented on src/web/index.php
> +    $state = $_GET['state'];
Думаю ця змінна не потрібна.

2022-09-09 18:56 UTC, Kloud333 commented on src/web/index.php
> +    $airports = array_filter(
Тут я б поправив форматування на таке -

```
    $airports = array_filter($airports, function ($airport) {
        return $airport['state'] == $_GET['state'];
    });
```

2022-09-09 18:56 UTC, Kloud333 commented on src/web/index.php
> +    function sortBy($param)
Думаю ця функція, яка має в собі ще одну функцію у середені зовсім не портібна. Краще використати її у функції `usort`. Вона має здатність використовувати `callback` функцію.

2022-09-09 18:56 UTC, Kloud333 commented on src/web/index.php
> +    usort($airports, sortBy($param));
Додав би сюди `callback` функцію з функції вище. 

```
    usort($airports, function ($a, $b) {
        return $a[$_GET['sort']] <=> $b[$_GET['sort']];
    });
```

2022-09-09 18:56 UTC, Kloud333 commented on tests/GetUniqueFirstLettersTest.php
> +        require_once './src/web/functions.php';
`require` ніколи не пишеться в середині коду. Винеси будь-ласка на верх там де `use`. І додай між ними пустий рядок.

2022-09-10 08:12 UTC, Ortemki commented on src/web/functions.php
> +    $letters = array_unique(array_map($firstLetter, $airports));
Переписал немного функцию getUniqueFirstLetters

2022-09-10 08:12 UTC, Ortemki commented on src/web/index.php
> +    $airports = array_filter(
Исправил .

2022-09-10 08:13 UTC, Ortemki commented on src/web/index.php
> +    $letter = $_GET['filter_by_first_letter'];
Удалил лишнею переменную.

2022-09-10 08:14 UTC, Ortemki commented on src/web/index.php
> +    $state = $_GET['state'];
Также удалил переменную $state.

2022-09-10 08:14 UTC, Ortemki commented on src/web/index.php
> +    $airports = array_filter(
Исправил запись функции сортировку по штатам.

2022-09-10 08:15 UTC, Ortemki commented on src/web/index.php
> +    function sortBy($param)
Переписал код что бы использовать эту функцию в usort.

2022-09-10 08:17 UTC, Ortemki commented on src/web/index.php
> +    usort($airports, sortBy($param));
Добавил функцию sortBy как callback функцию в usort.

2022-09-10 08:17 UTC, Ortemki commented on tests/GetUniqueFirstLettersTest.php
> +        require_once './src/web/functions.php';
Вынес подключения файла на верх кода.

2022-09-10 23:31 UTC, Kloud333 approved these changes

2022-09-11 08:21 UTC, merged